[package]
name = "sms3rs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
sms3rs-shared = { version = "*", path = "../shared" }
reqwest = { version = "0.11", features = ["json"] }
anyhow = "*"
serde = "1.0"
